import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarDesktop } from "@/components/SidebarDesktop";
import { ReduxProvider } from "@/components/ReduxProvider";
import { Notification } from "@/components/ui/Notification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row`}
      >
        <ReduxProvider>
          <SidebarDesktop />
          <Notification />
          <div className={"flex-1 flex-col items-center justify-start"}>
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
