<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>95b31d0f-aa4d-4955-8730-9b655b578286</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NCuid.NetCore" Version="1.0.1" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
      <Folder Include="Interfaces\" />
      <Folder Include="Repositories\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
